kind: wasmer.io/App.v0
owner: brianjien
name: career-tracker-dashboard
package: brianjien/career-tracker-dashboard
debug: true
locality:
  regions:
    - fr-pari1
capabilities:
  database:
    engine: mysql
health_checks:
  - http:
      method: get
      path: /api/health
      interval: 30s
      timeout: 10s
      unhealthy_threshold: 2
      healthy_threshold: 1
      expected_status_codes:
        - 200
